### ISSUE TITLE
Set up webpack

### ISSUE THREAD

**Issue by evanwchen** [unsinkablecircus/opengallery#2]

**Comment by jwdomingo** [comment]
# Resources

[Webpack Hot Middleware](https://github.com/glenjamin/webpack-hot-middleware)
[Ultimate Hot Reloading Example](https://github.com/glenjamin/ultimate-hot-reloading-example)

This might also be useful for Material-UI
[Webpack with Material-UI](https://github.com/callemall/material-ui/tree/master/examples/webpack-example)

**Comment by megaohms** [comment]
http://survivejs.com/webpack_react/developing_with_webpack/
https://webpack.github.io/docs/webpack-dev-server.html
